services:
    webserver:
        image: nginx:alpine
        container_name: je-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/mime.types:/etc/nginx/mime.types
        ports:
            - 8000:80
        networks:
            - default

    php-fpm:
        build:
            context: docker/php-fpm
            args:
                PHP_VERSION: ${PHP_VERSION}
        container_name: je-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/www-overrides.conf:/etc/php/${PHP_VERSION}/fpm/pool.d/z-overrides.conf