name: Deploy on production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        username: deploy
        host: jouonsensemble.org
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: GITHUB_REPOSITORY
        script: |
          chmod +x ~/deploy-jouonsensemble.sh
          ~/deploy-jouonsensemble.sh
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}